server:
  port: 8080
#H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dcbapp;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: qpay
    password: qpay
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#logging
logging:
  level:
    root: DEBUG