server:
  port: 8080
#aws rds config
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/quantum-pay
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#aws secrets manager configs
#aws:
 # secrets-manager:
 #   secret-id: AKIAYOCL6NLJUBM2JTRD
  #  secret-key: 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
   # roleArn: arn:aws:iam::579979864787:role/acbs-role
    #region: eu-north-1
    #secret-name: qpay-secret


#logging
logging:
  level:
    root: DEBUG