server:
  port: 8080
#H2
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quantum-pay
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#logging
logging:
  level:
    root: DEBUG